<?php


if ($this->messages):
    ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>       
        <?php foreach ($this->messages as $messages): ?>
            <strong>Success!</strong> <?php echo $messages ?>       
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="row-fluid">
  
    <div class="span3">
        <?php include_once(__DIR__.'/../../menu.phtml');?>
       
    </div>
    <div class="span9">
      


    </div>
</div>