<?php


if ($this->messages):
    ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>       
        <?php foreach ($this->messages as $messages): ?>
            <strong>Success!</strong> <?php echo $messages ?>       
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="row-fluid">
  
    <div class="span3">
        <ul class="nav nav-list">
            <li class="nav-header">HelpDesk</li>
            <li class="active"><a href="<?php echo $this->url('projetos-especiais/helpdesk');?>">Página principal</a></li>
            <li class=""><a href="<?php echo $this->url('projetos-especiais/helpdesk/indicadores');?>">Indicadores</a></li>
        </ul>
       
    </div>
    <div class="span9">
      


    </div>
</div>