<div class="row-fluid">

    <div class="span3">
        <?php include_once(__DIR__ . '/../../menu.phtml'); ?>


    </div>
    <div class="span9">        
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th align="center" colspan="3">
                        Estatística do último mês
                    </th>
                </tr>
                <tr>
                    <th>Total de chamados</th>
                    <th>Média total</th>
                    <th>Chamados abertos</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><?php echo $this->total_chamados; ?></td>
                    <td><?php echo $this->media; ?></td>
                    <td><?php echo $this->chamados_abertos; ?></td>
                </tr>
            </tbody>
        </table>


    </div>
</div>