<ul class="nav nav-list">
    <li class="nav-header">HelpDesk</li>
    <li><a href="<?php echo $this->url('projetos-especiais/helpdesk'); ?>">Página principal</a></li>
    <li><a href="<?php echo $this->url('categoria-chamado',array('setor'=>2)); ?>">Categoria de chamados</a></li>
    <li><a href="<?php echo $this->url('projetos-especiais/helpdesk/indicadores',array('setor'=>2)); ?>">Indicadores</a></li>
    
</ul>